### ISSUE TITLE
Couple of Bugs I found

### ISSUE THREAD

**Issue by Mravuri96** [rodydavis/storyboard#1]
Wonderfull package.

Understanding that this package is still in its infancy, just sharing a couple of bugs I encountered.

Responsive pages are breaking, as the Mediaquery isnt adhering the size from the screenSize property of the Storyboard package, I think that the size given in the screenSize property should override all the mediaquery calls.

![Screen Recording 2020-05-02 at 7 41 04 PM mov](https://user-images.githubusercontent.com/28457922/80897456-9e392f00-8cad-11ea-951f-6cd9c8bbddf2.gif)

Broken themeMode property of MaterialApp, causing darkmode/lightmode switching to not work
**Storyboard Behaviour**
![Storyboard Behaviour](https://user-images.githubusercontent.com/28457922/80897164-dd19b580-8caa-11ea-9d4a-1cf7a23a86bb.gif)

**Expected Behaviour**
![Expected Behaviour](https://user-images.githubusercontent.com/28457922/80897162-d8ed9800-8caa-11ea-8f06-ef33e4578098.gif)

**Comment by rodydavis** [comment]
This is super valuable! Will fix on the next release 😎 yeah I made this in 1 hour. So definitely looking for feedback
