### ISSUE TITLE
Make StoryBoard and DevicePreview play nice together - [device_preview]

### ISSUE THREAD

**Issue by rydmike** [rodydavis/storyboard#10]
If you wrap your Material app in a DevicePreview (https://pub.dev/packages/device_preview) and then in a StoryBoard, the screens presented in the story board do not get the correct media size.

![image](https://user-images.githubusercontent.com/39990307/81214669-d8be0700-8fe0-11ea-93cd-246381ad1764.png)

This happens also if the DevicePreview enabled property is set to false and StoryBoard is set true.

It would be great if DevicePreview and StoryBoard could play nicely together, at least when they are not enabled at the same time.

**Comment by rodydavis** [comment]
Can you share a code snippet so i have the correct code to test with?

**Comment by rodydavis** [comment]
Experiments are being done here: https://github.com/rodydavis/storyboard/tree/device_preview

**Comment by rodydavis** [comment]
Added device frames on 0.1.5!
