### ISSUE TITLE
Add device frames - [device_preview]

### ISSUE THREAD

**Issue by rydmike** [rodydavis/storyboard#11]
Wild idea for a new feature, add an option to show/select different device frames around the presented screens.

Maybe code for the device frames could be borrowed from DevicePreview.(https://pub.dev/packages/device_preview)

**Comment by rodydavis** [comment]
Experiments are being done here: https://github.com/rodydavis/storyboard/tree/device_preview

**Comment by rydmike** [comment]
Cool, looking forward to test it when it lands! :)

**Comment by rodydavis** [comment]
Added on 0.1.5!
