### ISSUE TITLE
Storyboard() use in MaterialApp as widget, does not pick up theme

### ISSUE THREAD

**Issue by rydmike** [rodydavis/storyboard#12]
When using Storyboard() in a MaterialApp as a widget, like in example "complete_custom_lanes_builder.dart", it does not pick up the theme of the MaterialApp it is used in.

Tested in version: 0.1.2+1

**Comment by rodydavis** [comment]
Fixed on version 0.1.3

**Comment by rydmike** [comment]
Tested and this work OK. Great fix actually critical since this was needed to make StoryBoard work properly as an in-material-app feature and not only as an app wrapper.. Thanks!
