### ISSUE TITLE
Ehancement: customLanes - Children cannot have a label

### ISSUE THREAD

**Issue by rydmike** [rodydavis/storyboard#17]
When using StoryBoard() and the customLanes, the children in a CustomLane cannot have a label! 
Consider possibility to add a custom label text for each child.

When using StoryBoard.material() and wrapping a material app in it, each screen automatically get a nice label corresponding to the route by default. In customLanes there is no way to add a similar label even manually when defining the custom content of the lanes, by e.g. providing one for selected/all children in a CustomLane. Would be nice if this was possible.

**Comment by rodydavis** [comment]
Fixed on version 0.1.3

**Comment by rydmike** [comment]
Tested, works great, thanks!  Really nice to be able to do this on customLanes too. :)
