### ISSUE TITLE
Feature: Passing Route Arguments

### ISSUE THREAD

**Issue by ArneSaknussemm89** [rodydavis/storyboard#4]
Looks like a really cool package but having an issue with using it as it doesn't allow for passing test arguments to each route.

I have multiple routes the fetch arguments passed to the Route from the Navigator, so for those screens I don't get a good preview. It looks like each route is being built with a RouteSettings widget, so perhaps adding something like this would work?

```
Map<String, dynamic> routeArguments;
```

Then those could be used to match the route name in that Map, grab the arguments and pass them to the RouteSettings in `flutter_storyboard.dart:267`?

**Comment by rodydavis** [comment]
Yep looking for a way to pass the arguments object! I’ll fix this today 😎

**Comment by rodydavis** [comment]
Fixed on version v0.0.4
