### ISSUE TITLE
DarkMode: Consider some border around the screens

### ISSUE THREAD

**Issue by rydmike** [rodydavis/storyboard#6]
In light theme mode the elevation of the screens works well on the presentation canvas:

![image](https://user-images.githubusercontent.com/39990307/81207492-4add1e80-8fd6-11ea-9cb7-bfd169d23206.png)

However, in dark mode the screens may become a bit too "embedded" with the canvas background:

![image](https://user-images.githubusercontent.com/39990307/81207727-aeffe280-8fd6-11ea-958d-9bf174bd11df.png)

Especially in a "true black" mode:

![image](https://user-images.githubusercontent.com/39990307/81207773-c17a1c00-8fd6-11ea-929d-10fef13509b9.png)

**SOLUTION PROPOSAL 1:**

Add optional separate border styles for the light/dark theme that can be provided/turned on, if so desired.

**SOLUTION PROPOSAL 2:**

Provide color properties where user can specify background colors for the light and and dark theme modes, for the background canvas that presents the screens.
This would allow users to specify a background color for the presentation canvas in light and/or dark modes, that are different from the canvas background color used in the theme for the application itself. It then becomes possible to use light/dark background colors that are slightly different from light/dark colors used in the presented application. It of course also allows for totally custom silly background colors of course, which could also be useful in some cases.

Options 1 and 2 are of course not mutually exclusive, they could both be useful alternatives individually or together.

**Comment by rodydavis** [comment]
Fixed on version 0.1.2! Added box shadows, but i will add more options later

**Comment by rydmike** [comment]
Thanks, look better now, also with the customLanes builder I can theme the lane background to whatever color desired for light and dark theme lane background, so this works great!

Can make it much prettier now, like so for example:

![image](https://user-images.githubusercontent.com/39990307/81665023-daf0ed00-9448-11ea-9b07-efef2a2a87d4.png)
