### ISSUE TITLE
Reset scaling and offset is reset to coded defaults

### ISSUE THREAD

**Issue by rydmike** [rodydavis/storyboard#8]
When you use the reset button to reset the view port settings, it resets to the "hard coded" defaults. It would be nice if it would reset to value(s) that were provided in the widget constructor first, for scaling and offset, and only if such values where not provided in the constructor, would it reset to hard coded defaults.

![image](https://user-images.githubusercontent.com/39990307/81210034-f76ccf80-8fd9-11ea-8119-fd6eba7cede4.png)

**Comment by rodydavis** [comment]
Fixed on version 0.1.0!

**Comment by rydmike** [comment]
Tested and works fine, thx!
