### ISSUE TITLE
IDEA: Consider a way to present screens in different groups and lanes

### ISSUE THREAD

**Issue by rydmike** [rodydavis/storyboard#9]
This is just a suggestion for a new feature, but it would be useful to be able to group presented screens into different groups and lanes.
 
Basically a way to decided when to start a new row and also to show lane headers, maybe even headers within a lane, if you want to divide stuff on the same row in some cases too. Here is a quick mockup example:

![image](https://user-images.githubusercontent.com/39990307/81212712-f047c080-8fdd-11ea-899b-3c4c2c21c83a.png)

The group and lane headers could have some default design, optionally a custom template widget could be provided for it.

Maybe this kind of layout could be done by providing some kind of heading and break "widgets" in desired order the customScreens lists. An option to hide initialRoute/home is then also needed so we do not get it shown first on a row of its own all the time. Naturally there are many ways of doing this, this was just an idea to build upon some already existing features that might be easy to extend to encompass the feature as well.

**Comment by rodydavis** [comment]
Added on version 0.1.1!

**Comment by rydmike** [comment]
Tested and works great, thanks!
